name: "CI"
on:
  pull_request:
    branches:
      - '**'
      # - '*'         # matches every branch that doesn't contain a '/'
      # - '*/*'       # matches every branch containing a single '/'
      # - '**'        # matches every branch
      # - '!main'   # excludes main

jobs:
  gradle-task:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout to pr branch
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Set up gradle with gradle cache
        uses: gradle/actions/setup-gradle@v3
        continue-on-error: true
        with:
          add-job-summary-as-pr-comment: on-failure
          gradle-version: 8.8
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}

      - name: Build
        run: gradle build -x check --configuration-cache --info

      - name: Test (Junit5)
        run: gradle test --configuration-cache --info
        continue-on-error: true

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: './build/test-results/**/TEST-*.xml'
          check_name: 'Test'