/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.dto.Chunk;
import org.example.dto.EthernetHeader;
import org.example.dto.TCPHeader;
import org.example.layer.EthernetLayer;
import org.example.layer.InternetLayer;
import org.example.layer.Layer;

import java.util.Arrays;

public class App {
    private final static Layer ip = InternetLayer.getInstance();
    private final static Layer ethernet = EthernetLayer.getInstance();

    public static void main(String[] args) {
        ip.setLowerLayer(ethernet);
        ethernet.setUpperLayer(ip);

        Chunk sendMsg = ip.send(new Chunk(new TCPHeader(), new byte[] {0, 1, 0, 1}));
        Chunk receiveMsg = ethernet.receive(new Chunk(new EthernetHeader(), new byte[] {0, 1, 0, 1}));

        System.out.print("Ethernet Payload(IP Header + Data) : ");
        System.out.println(Arrays.toString(sendMsg.getData()));
        System.out.print("Ethernet Header : ");
        System.out.println(Arrays.toString(sendMsg.getHeader().toByteArr()));
        System.out.print("Data : ");
        System.out.println(Arrays.toString(receiveMsg.getData()));
        System.out.print("IP Header : ");
        System.out.println(Arrays.toString(receiveMsg.getHeader().toByteArr()));
    }
}
